runtime: go114

handlers:
- url: /.well-known/acme-challenge/(.*)
  mime_type: text/plain
  static_files: well-known/acme-challenge/\1
  upload: well-known/acme-challenge/.*

- url: /static
  static_dir: static

- url: /.*
  script: auto